from . import account_account
from . import account_fiscal_position
from . import account_journal
from . import account_move
from . import account_move_line
from . import account_payment_register
from . import account_payment_method
from . import account_tax
from . import account_tax_group
from . import mail_template
from . import payment_transaction
from . import product_template
from . import res_company
from . import res_config_settings
from . import res_partner
from . import res_users
