# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "BANKayma",
    "summary": "BANKayma base module",
    "version": "16.0.1.0.2",
    "development_status": "Alpha",
    "author": "Moshchot Coop",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "association",
        "attachment_indexation",
        "base_user_effective_permissions",
        "board",
        "barcodes_gs1_nomenclature",
        "base_view_inheritance_extension",
        "contacts",
        "document_knowledge",
        "document_page_approval",
        "event",
        "mail_debrand",
        "mail_discuss_security",
        "mail_tracking_mass_mailing",
        "mass_mailing_list_dynamic",
        "mass_mailing_partner",
        "membership",
        "disable_odoo_online",
        "base_portal_type",
        "module_auto_update",
        "portal_odoo_debranding",
        "remove_odoo_enterprise",
        "res_company_code",
        "web_company_color",
        "web_responsive",
        "web_select_all_companies",
        "res_company_code",
        "spreadsheet_dashboard_oca",
        "spreadsheet_board",
        "hr",
        "hr_contract",
        "hr_hourly_cost",
        "hr_org_chart",
        "partner_contact_access_link",
        "partner_contact_lang",
        "portal_rating",
        "project",
        "project_department",
        "project_parent_task_filter",
        "project_role",
        "project_sms",
        "project_task_add_very_high",
        "project_task_default_stage",
        "project_task_personal_stage_auto_fold",
        "project_template",
        "project_timeline",
        "project_type",
        "res_company_category",
        "server_action_mass_edit",
        "social_media",
        "web_advanced_search",
        "web_chatter_position",
        "web_dark_mode",
        "web_dashboard_open_action",
        "website_blog",
        "website_form_project",
        "website_mail",
        "website_partner",
        "website_payment",
        "web_theme_classic",
        "web_timeline",
        "web_widget_pattern",
    ],
    "data": [
        "data/mail_message_subtype.xml",
        "data/res_company.xml",
        "data/res_users.xml",
        "security/bankayma_base.xml",
        "security/ir.model.access.csv",
        "data/mailing_list.xml",
        "views/res_company.xml",
        "views/res_company_category.xml",
        "views/res_partner.xml",
        "views/res_users.xml",
        "views/templates.xml",
        "views/mail_compose_message.xml",
        "views/mail_template.xml",
        "views/menu.xml",
    ],
    "demo": [
        "demo/res_company.xml",
        "demo/res_users.xml",
    ],
    "website": "https://github.com/moshchot/BANKayma",
    "external_dependencies": {
        "python": [
            "astor",
            "openupgradelib",
            "odoo_test_helper",
        ]
    },
    "assets": {
        "web.assets_backend": [
            "bankayma_base/static/src/css/*backend.css",
            "bankayma_base/static/src/js/*.esm.js",
            "bankayma_base/static/src/xml/*.xml",
        ],
        "web.assets_frontend": [
            "bankayma_base/static/src/css/*frontend.css",
        ],
    },
}
