# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "BANKayma (website)",
    "summary": "BANKayma website customizations",
    "version": "16.0.1.0.1",
    "development_status": "Alpha",
    "author": "Moshchot Coop",
    "license": "AGPL-3",
    "application": True,
    "depends": [
        "bankayma_account",
        "website_event_questions",
        "website_event_track",
        "partner_multi_relation",
        "res_company_category",
    ],
    "data": [
        "data/event_type.xml",
        "data/product_category.xml",
        "data/res_partner_relation_type.xml",
        "data/ir_asset.xml",
        "security/bankayma_website.xml",
        "security/ir.model.access.csv",
        "templates/company_page.xml",
        "templates/company_page_embed.xml",
        "templates/company_list.xml",
        "templates/website.xml",
        "templates/website_blog.xml",
        "templates/website_event.xml",
        "views/blog_post.xml",
        "views/menu.xml",
        "views/res_company.xml",
        "views/res_company_category.xml",
        "wizards/bankayma_project_page_embed_code.xml",
    ],
    "demo": [
        "demo/res_users.xml",
    ],
    "website": "https://github.com/moshchot/BANKayma",
    "external_dependencies": {"python": []},
    "assets": {
        "web.assets_frontend": [
            "/bankayma_website/static/src/components/*.js",
            "/bankayma_website/static/src/components/*.xml",
            "/bankayma_website/static/src/components/*.scss",
            "/bankayma_website/static/src/scss/website_event.scss",
            "/bankayma_website/static/src/scss/bankayma_website.scss",
        ],
        "website.assets_editor": [
            "/bankayma_website/static/src/components_editor/*.js",
        ],
    },
}
